#exception handling
try:
    print(a)
except:
    print("error!!!")
